language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
       apt:
         packages:
           - cmake-data
           - cmake
           - libgtest-dev

before_script:
  - cd /usr/src/gtest
  - cmake CMakeLists.txt
  - make
  - cp *.a /usr/lib

script:
     - mkdir -p build
     - cd build
     - cmake ../
     - make
     - ctest -V
